# Generated by Django 4.2.11 on 2024-03-08 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_datasettable_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMonitorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('row_count', models.IntegerField()),
                ('column_count', models.IntegerField()),
                ('dataset_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.datasettable')),
            ],
        ),
    ]
