# Generated by Django 4.2.9 on 2024-02-23 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_extension', models.CharField(max_length=255, null=True)),
                ('features', models.CharField(default='all', max_length=511, null=True)),
                ('target', models.CharField(default='all', max_length=255, null=True)),
                ('user', models.IntegerField()),
                ('dataset', models.CharField(max_length=255, null=True)),
                ('model_file', models.BinaryField(null=True)),
            ],
        ),
    ]
