# Generated by Django 4.2.9 on 2024-02-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='user',
        ),
    ]
