# Generated by Django 4.2.9 on 2024-02-29 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_remove_mlmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMonitorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.CharField(max_length=255, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
            ],
        ),
    ]
