# Generated by Django 4.2.9 on 2024-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_datasetmonitorlog_unacknowledged_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='activation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='batch_size',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='epocs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='hidden_layers',
            field=models.TextField(default='100,100', null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='input_shape',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='optimizer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='output_shape',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='task',
            field=models.CharField(choices=[('Regression', 'Regression'), ('Classification', 'Classification'), ('Anomaly Detection', 'Anomaly Detection')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='timesteps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='target',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
