# Generated by Django 4.2.9 on 2024-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_mlmodel_activation_mlmodel_batch_size_mlmodel_epocs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='max_depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='num_trees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('untrained', 'Untrained'), ('trained', 'Trained'), ('training', 'Training')], default='untrained', max_length=255),
        ),
    ]
