# Generated by Django 4.2.9 on 2024-03-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0006_mlmodel_max_depth_mlmodel_num_trees_mlmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='epocs',
            new_name='epochs',
        ),
    ]
