# Generated by Django 4.2.9 on 2024-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0007_rename_epocs_mlmodel_epochs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='last_trained',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='sample_frac',
            field=models.FloatField(default=0.8, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='sample_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='scaler',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='training_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='activation',
            field=models.CharField(default='relu', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='max_depth',
            field=models.IntegerField(default=16, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='num_trees',
            field=models.IntegerField(default=300, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='optimizer',
            field=models.CharField(default='adam', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='timesteps',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
