# Generated by Django 4.2.9 on 2024-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0008_mlmodel_last_trained_mlmodel_sample_frac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='scaler_file',
            field=models.BinaryField(null=True),
        ),
    ]
