# Generated by Django 4.2.9 on 2024-03-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0009_mlmodel_scaler_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='default_model',
            field=models.BooleanField(default=False),
        ),
    ]
