# Generated by Django 4.2.9 on 2024-03-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0010_mlmodel_default_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='task',
            field=models.CharField(choices=[('Regression', 'Regression'), ('Classification', 'Classification'), ('Binary', 'Binary Classification'), ('Anomaly Detection', 'Anomaly Detection')], max_length=255, null=True),
        ),
    ]
